version: '3.4'

services:
  bluecustomer.api:
    image: ${DOCKER_REGISTRY-}bluecustomerapi
    build:
      context: .
      dockerfile: source/BlueCustomer.Api/Dockerfile
    depends_on:
      - bluecustomer.infrastructure
    environment:
      - "ConnectionStrings__Blue=Server=mssql;Database=Blue;User Id=SA;Password=Blue@Password1234" 
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Blue@Password1234"
      ACCEPT_EULA: "Y"

