version: '3.4'

services:
  bluecustomer.api:
    image: ${DOCKER_REGISTRY-}bluecustomerapi
    ports:
      - "8081:80"
      - "80"
    build:
      context: source
      dockerfile: BlueCustomer.Api/Dockerfile
    depends_on:
      - bluecustomer.infrastructure
    environment:
      - "ConnectionStrings__Blue=Server=mssql;Database=Blue;User Id=SA;Password=Blue@Password1234" 
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "4563:1433"
      - "1433"
    environment:
      SA_PASSWORD: "Blue@Password1234"
      ACCEPT_EULA: "Y"
